let teams = [
  {
    Id: "1",
    Name: "Kolkata Knight Riders",
    : "KKR",
    Captain_Name: "Shreyas",
    Captain_ID: 12,
    Logo: "./images/kkr_team.jpeg",
    Top_BaShort_Codetsman: "SHREYAS AYAR",
    Top_Bowler: "Mavi",
    Total_Player: 15,
    Total_Wins: 3,
  },
  {
    Id: "2",
    Name: "Royal Challengers Bangalore",
    Short_Code: "RCB",
    Captain_Name: "Virat",
    Captain_ID: 12,
    Logo: "./images/rcb_team.jpeg",
    Top_Batsman: "VIRAT",
    Top_Bowler: "CHAHAL",
    Total_Player: 15,
    Total_Wins: 3,
  },
  {
    Id: "3",
    Name: "Chennai Super Kings",
    Short_Code: "CSK",
    Captain_Name: "Dhoni",
    Captain_ID: 12,
    Logo: "./images/csk_team.jpeg",
    Top_Batsman: "DHONI",
    Top_Bowler: "BRAVO",
    Total_Player: 15,
    Total_Wins: 3,
  },
  {
    Id: "4",
    Name: "Kings XI Punjab",
    Short_Code: "KXIP",
    Captain_Name: "Mayank",
    Captain_ID: 12,
    Logo: "./images/kxip_team.jpeg",
    Top_Batsman: "MAYANK",
    Top_Bowler: "ASHWIN",
    Total_Player: 15,
    Total_Wins: 3,
  },
  {
    Id: "5",
    Name: "Rajasthan Royals",
    Short_Code: "RR",
    Captain_Name: "Sanju",
    Captain_ID: 12,
    Logo: "./images/rr_team.jpeg",
    Top_Batsman: "SANJU SAMSON",
    Top_Bowler: "Mavi",
    Total_Player: 15,
    Total_Wins: 3,
  },
  {
    Id: "6",
    Name: "Delhi Captials",
    Short_Code: "DD",
    Captain_Name: "Rishabh Pant",
    Captain_ID: 12,
    Logo: "./images/dc_team.jpeg",
    Top_Batsman: "RISHABH PANT",
    Top_Bowler: "Mavi",
    Total_Player: 15,
    Total_Wins: 3,
  },
  {
    Id: "7",
    Name: "Mumbai Indians",
    Short_Code: "MI",
    Captain_Name: "Rohit",
    Captain_ID: 12,
    Logo: "./images/mi_team.jpeg",
    Top_Batsman: "ROHIT SHARMA",
    Top_Bowler: "Bumrah",
    Total_Player: 15,
    Total_Wins: 3,
  },
  {
    Id: "8",
    Name: "Sunrisers Hyderabad",
    Short_Code: "SRH",
    Captain_Name: "Kane",
    Captain_ID: 12,
    Logo: "./images/sh_team.jpeg",
    Top_Batsman: "KANE",
    Top_Bowler: "BHUBANESWAR",
    Total_Player: 15,
    Total_Wins: 3,
  },
  {
    Id: "9",
    Name: "Lucknow Super Giants",
    Short_Code: "LSG",
    Captain_Name: "KL Rahul",
    Captain_ID: 12,
    Logo: "./images/lsg_team.jpeg",
    Top_Batsman: "KL RAHUL",
    Top_Bowler: "RAHUL CHAHAR",
    Total_Player: 15,
    Total_Wins: 3,
  },
  {
    Id: "10",
    Name: "Gujarat Titans",
    Short_Code: "GT",
    Captain_Name: "Hardik",
    Captain_ID: 12,
    Logo: "./images/gt_team.jpeg",
    Top_Batsman: "HARDIK",
    Top_Bowler: "SHAMI",
    Total_Player: 15,
    Total_Wins: 3,
  },
];
